name: Daily Issue Changelog

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run changelog script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_REPO: 'PluginBugs/Issues-ItemsAdder'
          TARGET_REPO: ${{ github.repository }}
          TARGET_ISSUE: 5
        run: python scripts/issue_changelog.py
      - name: Commit updated snapshot
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add issue_snapshot.json
          git commit -m "Update issue snapshot" || echo "No changes to commit"
          git push
