on: 
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: radcortez/milestone-release-action@main
      name: milestone release
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        milestone-title: ${{github.event.milestone.title}}