on:
  milestone:
    type: [closed]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Build Changelog
        id: github_release
        uses: okcredit/changelog-creator-action@1.0.0
        with:
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print change log
        run: echo "Generated changelog - ${{ steps.github_release.outputs.changelog }}"
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.github_release.outputs.milestone }}
          release_name: ${{ steps.github_release.outputs.milestone }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}